### ISSUE TITLE
Mouse presses sometimes do not get recognized 

### ISSUE THREAD

**Issue by MrMineDe** [ws-kj/xsnip#9]
I did not figure out exactly when this behavior happens, but sometimes (most of the time, when the computer is already running for a bit and after running xsnip a few times already. It usually only starts working again after rebooting) xsnip does not react to me pressing the left or right mouse button. It closes when pressing escape though.

I have the suspicion that something goes wrong in XQueryPointer() but I couldn't find any similar sounding problems and am no expert when it comes to xorg. 

Also, thank you very much for this little program, it is great!

**Comment by funnyboy-roks** [comment]
I had a similar issue and fixed it on my fork of this project, which you can find here: https://github.com/funnyboy-roks/xsnip/

Let me know if that works for you so I can create a PR here.

**Comment by MrMineDe** [comment]
Hey,
I am testing the fork right now, but so far no crashes, so looks good :+1: thanks for sharing!
I'll reopen the issue if the problem appears again
